version: "3"
services:
  db:
    container_name: postgres_con
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - pgdata:/var/lib/postgresql/data
  nextjs:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - db
volumes:
  pgdata: {}
  db:
    external: true
