version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres_con
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
volumes:
  pgdata: {}
  db:
    external: true
